### PR TITLE
Remove cb example + remove kie maven plugin usage + remove lastmodified

### PR DESCRIPTION
**Pull request by ge0ffrey**
Remove cb example + remove kie maven plugin usage (to avoid snapshot version like drools playground) + remove lastmodified file

### CODE REVIEW

**Comment by ge0ffrey** [comment]
When I clone that repo from optaplanner-wb-webapp I did get:

```
ERROR [io.undertow.request] UT005023: Exception handling request to /out.81652-61128.erraiBus: java.lang.RuntimeException: no marshaller for type: org.guvnor.structure.repositories.RepositoryEnvironmentConfigurations
    at org.jboss.errai.marshalling.client.marshallers.AbstractCollectionMarshaller.marshallToCollection(AbstractCollectionMarshaller.java:87) [errai-marshalling-4.0.0-20160302.183329-75.jar:4.0.0-SNAPSHOT]
    at org.jboss.errai.marshalling.client.marshallers.ListMarshaller.doDemarshall(ListMarshaller.java:47) [errai-marshalling-4.0.0-20160302.183329-75.jar:4.0.0-SNAPSHOT]
    at org.jboss.errai.marshalling.client.marshallers.ListMarshaller.doDemarshall(ListMarshaller.java:34) [errai-marshalling-4.0.0-20160302.183329-75.jar:4.0.0-SNAPSHOT]
    at org.jboss.errai.marshalling.client.marshallers.AbstractCollectionMarshaller.doDemarshall(AbstractCollectionMarshaller.java:48) [errai-marshalling-4.0.0-20160302.183329-75.jar:4.0.0-SNAPSHOT]
    at org.jboss.errai.marshalling.client.marshallers.AbstractCollectionMarshaller.doDemarshall(AbstractCollectionMarshaller.java:33) [errai-marshalling-4.0.0-20160302.183329-75.jar:4.0.0-SNAPSHOT]
    at org.jboss.errai.marshalling.client.marshallers.AbstractBackReferencingMarshaller.demarshall(AbstractBackReferencingMarshaller.java:76) [errai-marshalling-4.0.0-20160302.183329-75.jar:4.0.0-SNAPSHOT]
    at org.jboss.errai.marshalling.client.marshallers.ErraiProtocolEnvelopeMarshaller.doDemarshall(ErraiProtocolEnvelopeMarshaller.java:68) [errai-marshalling-4.0.0-20160302.183329-75.jar:4.0.0-SNAPSHOT]
    at org.jboss.errai.marshalling.client.marshallers.ErraiProtocolEnvelopeMarshaller.demarshall(ErraiProtocolEnvelopeMarshaller.java:39) [errai-marshalling-4.0.0-20160302.183329-75.jar:4.0.0-SNAPSHOT]
    at org.jboss.errai.bus.server.io.MessageFactory.getParts(MessageFactory.java:151) [errai-bus-4.0.0-20160302.184626-75.jar:4.0.0-SNAPSHOT]
    at org.jboss.errai.bus.server.io.MessageFactory.createCommandMessage(MessageFactory.java:100) [errai-bus-4.0.0-20160302.184626-75.jar:4.0.0-SNAPSHOT]
    at org.jboss.errai.bus.server.servlet.DefaultBlockingServlet.doPost(DefaultBlockingServlet.java:142) [errai-bus-4.0.0-20160302.184626-75.jar:4.0.0-SNAPSHOT]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) [jboss-servlet-api_3.1_spec-1.0.0.Final.jar:1.0.0.Final]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [jboss-servlet-api_3.1_spec-1.0.0.Final.jar:1.0.0.Final]
    at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85) [undertow-servlet-1.0.15.Final.jar:1.0.15.Final]
    at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:130) [undertow-servlet-1.0.15.Final.jar:1.0.15.Final]
    at org.picketlink.authentication.web.AuthenticationFilter.doFilter(AuthenticationFilter.java:170) [picketlink-api-2.6.0.Final.jar:]
    at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:60) [undertow-servlet-1.0.15.Final.jar:1.0.15.Final]
    at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:132) [undertow-servlet-1.0.15.Final.jar:1.0.15.Final]
    at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:85) [undertow-servlet-1.0.15.Final.jar:1.0.15.Final]
    at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:61) [undertow-servlet-1.0.15.Final.jar:1.0.15.Final]
    at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) [undertow-servlet-1.0.15.Final.jar:1.0.15.Final]
    at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:25) [undertow-core-1.0.15.Final.jar:1.0.15.Final]
    at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:113) [undertow-servlet-1.0.15.Final.jar:1.0.15.Final]
    at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:56) [undertow-servlet-1.0.15.Final.jar:1.0.15.Final]
    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:25) [undertow-core-1.0.15.Final.jar:1.0.15.Final]
    at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:45) [undertow-core-1.0.15.Final.jar:1.0.15.Final]
    at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:61) [undertow-servlet-1.0.15.Final.jar:1.0.15.Final]
    at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:58) [undertow-core-1.0.15.Final.jar:1.0.15.Final]
    at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:70) [undertow-servlet-1.0.15.Final.jar:1.0.15.Final]
    at io.undertow.security.handlers.SecurityInitialHandler.handleRequest(SecurityInitialHandler.java:76) [undertow-core-1.0.15.Final.jar:1.0.15.Final]
    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:25) [undertow-core-1.0.15.Final.jar:1.0.15.Final]
    at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:25) [undertow-core-1.0.15.Final.jar:1.0.15.Final]
    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:25) [undertow-core-1.0.15.Final.jar:1.0.15.Final]
    at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:240) [undertow-servlet-1.0.15.Final.jar:1.0.15.Final]
    at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:227) [undertow-servlet-1.0.15.Final.jar:1.0.15.Final]
    at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:73) [undertow-servlet-1.0.15.Final.jar:1.0.15.Final]
    at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:146) [undertow-servlet-1.0.15.Final.jar:1.0.15.Final]
    at io.undertow.server.Connectors.executeRootHandler(Connectors.java:177) [undertow-core-1.0.15.Final.jar:1.0.15.Final]
    at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:727) [undertow-core-1.0.15.Final.jar:1.0.15.Final]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [rt.jar:1.8.0_72]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [rt.jar:1.8.0_72]

```

but that doesn't seem to be relevant.

**Comment by ge0ffrey** [comment]
I get the same exception by cloning the repo without this PR, so it's not related to the changes in this PR

```
ERROR [io.undertow.request] UT005023: Exception handling request to /out.85151-15698.erraiBus: java.lang.RuntimeException: no marshaller for type: org.guvnor.structure.repositories.RepositoryEnvironmentConfigurations
    at org.jboss.errai.marshalling.client.marshallers.AbstractCollectionMarshaller.marshallToCollection(AbstractCollectionMarshaller.java:87) [errai-marshalling-4.0.0-20160310.010915-86.jar:4.0.0-SNAPSHOT]
```

**Comment by Rikkola** [comment]
I recently did a change related to org.uberfire.java.nio.file.FileAlreadyExistsException. Need to check if the webapp is missing a dependency or something.

**Comment by Rikkola** [comment]
https://github.com/guvnorngtestuser1/optaplanner-playground/commit/d4419a117c24c22a35fabc076c9dce76b6058cf3

**Pull request closed without merging**
